# Generated by Django 5.0.6 on 2024-06-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Sobre_Nome', models.CharField(max_length=50)),
                ('Idade', models.IntegerField()),
            ],
        ),
    ]
